model:
  d_model: 512

vision_encoder:
  model_name: convnextv2_pico
  pretrained: true
  in_chans: 1
  drop_path_rate: 0.1

text_decoder:
  nhead: 8
  num_layers: 4
  dim_feedforward: 2048
  dropout: 0.1
